"""Backend model contracts and implementations for Tentgent runtime."""

from .base import (
    BackendConcurrencyPolicy,
    BackendFamily,
    BackendModel,
)
from .audio_speech import (
    AudioSpeechBackendModel,
    AudioSpeechModelFactory,
    AudioSpeechModelKind,
    AudioSpeechOutputFormat,
    AudioSpeechRequest,
    AudioSpeechResult,
    build_audio_speech_model,
)
from .audio_transcription import (
    AudioTranscriptionBackendModel,
    AudioTranscriptionModelFactory,
    AudioTranscriptionModelKind,
    AudioTranscriptionOutputFormat,
    AudioTranscriptionRequest,
    AudioTranscriptionResult,
    build_audio_transcription_model,
)
from .chat import (
    ChatBackendModel,
    ChatMessage,
    ChatModelFactory,
    ChatModelKind,
    ChatRequest,
    ChatResult,
    build_chat_model,
)
from .diffusers import DiffusersBackendModel
from .embedding import (
    EmbeddingBackendModel,
    EmbeddingModelFactory,
    EmbeddingModelKind,
    EmbeddingRequest,
    EmbeddingResult,
    EmbeddingVector,
    build_embedding_model,
)
from .image_generation import (
    ImageGenerationAdapterSelection,
    ImageGenerationBackendModel,
    ImageGenerationControlSelection,
    ImageGenerationModelFactory,
    ImageGenerationModelKind,
    ImageGenerationOutputFormat,
    ImageGenerationRequest,
    ImageGenerationResult,
    ImageGenerationWorkflowKind,
    build_image_generation_model,
)
from .llama_cpp import LlamaCppBackendModel
from .mlx import MlxBackendModel
from .records import (
    AdapterRecord,
    AdapterType,
    ModelCapability,
    ModelFormat,
    ModelRecord,
)
from .rerank import (
    RerankBackendModel,
    RerankModelFactory,
    RerankModelKind,
    RerankRequest,
    RerankResult,
    RerankScore,
    build_rerank_model,
    ranked_scores,
)
from .transformers import TransformersBackendModel
from .vision_chat import (
    VisionChatBackendModel,
    VisionChatModelFactory,
    VisionChatModelKind,
    VisionChatOutputFormat,
    VisionChatRequest,
    VisionChatResult,
    build_vision_chat_model,
)

__all__ = [
    "AdapterRecord",
    "AdapterType",
    "AudioSpeechBackendModel",
    "AudioSpeechModelFactory",
    "AudioSpeechModelKind",
    "AudioSpeechOutputFormat",
    "AudioSpeechRequest",
    "AudioSpeechResult",
    "AudioTranscriptionBackendModel",
    "AudioTranscriptionModelFactory",
    "AudioTranscriptionModelKind",
    "AudioTranscriptionOutputFormat",
    "AudioTranscriptionRequest",
    "AudioTranscriptionResult",
    "BackendConcurrencyPolicy",
    "BackendFamily",
    "BackendModel",
    "ChatBackendModel",
    "ChatMessage",
    "ChatModelFactory",
    "ChatModelKind",
    "ChatRequest",
    "ChatResult",
    "DiffusersBackendModel",
    "EmbeddingBackendModel",
    "EmbeddingModelFactory",
    "EmbeddingModelKind",
    "EmbeddingRequest",
    "EmbeddingResult",
    "EmbeddingVector",
    "ImageGenerationAdapterSelection",
    "ImageGenerationBackendModel",
    "ImageGenerationControlSelection",
    "ImageGenerationModelFactory",
    "ImageGenerationModelKind",
    "ImageGenerationOutputFormat",
    "ImageGenerationRequest",
    "ImageGenerationResult",
    "ImageGenerationWorkflowKind",
    "LlamaCppBackendModel",
    "MlxBackendModel",
    "ModelCapability",
    "ModelFormat",
    "ModelRecord",
    "RerankBackendModel",
    "RerankModelFactory",
    "RerankModelKind",
    "RerankRequest",
    "RerankResult",
    "RerankScore",
    "TransformersBackendModel",
    "VisionChatBackendModel",
    "VisionChatModelFactory",
    "VisionChatModelKind",
    "VisionChatOutputFormat",
    "VisionChatRequest",
    "VisionChatResult",
    "build_audio_speech_model",
    "build_audio_transcription_model",
    "build_chat_model",
    "build_embedding_model",
    "build_image_generation_model",
    "build_rerank_model",
    "build_vision_chat_model",
    "ranked_scores",
]
