pub mod adapter;
pub mod audio;
pub mod auth;
pub mod chat;
pub mod daemon;
pub mod dataset;
pub mod doctor;
pub mod embedding;
pub mod health;
pub mod jobs;
pub mod model;
pub mod rerank;
pub mod server;
pub mod session;
pub mod status;
mod store_jobs;
pub mod train;
pub mod vision;
